// Generated by CoffeeScript 2.0.0-beta2
(function() {
  var fetch, https, options, password, pimaticPort, pimaticUrl, processJSON, url, username;

  fetch = require('node-fetch');

  options = {
    method: 'GET'
  };

  username = "admin";

  password = "admin";

  pimaticUrl = "localhost";

  pimaticPort = 80;

  https = false;

  url = https ? "https://" : "http://" + `${username}:${password}@${pimaticUrl}:${pimaticPort}/api/devices`;

  fetch(url, options).then(function(res) {
    if (!res.ok) {
      console.log(`Error: Response ${res.status} - ${res.statusText}`);
      return null;
    } else {
      return res.json();
    }
  }).then(function(json) {
    if (json != null) {
      return processJSON(json);
    }
  }).catch(function(err) {
    return console.log(err);
  });

  processJSON = function({devices}) {
    var device, i, len, ref, results;
    ref = devices.slice(0, 6);
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      device = ref[i];
      results.push(console.log(device));
    }
    return results;
  };

}).call(this);
